export { default as Navbar } from "./navbar/Navbar"
export { default as Header } from "./header/Header"
export { default as HomeContent } from "./homeContent/HomeContent"
export { default as ParallaxScroll } from "./parallaxScroll/ParallaxScroll"
export { default as Skills } from "./skills/Skills"
export { default as Portfolio } from "./portfolio/Portfolio"
export { default as Footer } from "./footer/Footer"
